version: 2
updates:
  # Frontend dependencies (bun/npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
      build-tools:
        patterns:
          - "typescript"
          - "eslint*"
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"

  # Backend dependencies (Go modules)
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Shared dependencies (Go modules)
  - package-ecosystem: "gomod"
    directory: "/shared"
    schedule:
      interval: "weekly"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
