version: 2
updates:
  # Frontend dependencies (bun/npm)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "nyasuto"
    assignees:
      - "nyasuto"
    commit-message:
      prefix: "chore(frontend)"
      include: "scope"
    groups:
      react-ecosystem:
        patterns:
          - "react*"
          - "@types/react*"
      nextjs-ecosystem:
        patterns:
          - "next*"
          - "@next/*"
      build-tools:
        patterns:
          - "typescript"
          - "eslint*"
          - "tailwindcss"
          - "postcss"
          - "autoprefixer"

  # Backend dependencies (Go modules)
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "nyasuto"
    assignees:
      - "nyasuto"
    commit-message:
      prefix: "chore(backend)"
      include: "scope"

  # Shared dependencies (Go modules)
  - package-ecosystem: "gomod"
    directory: "/shared"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "nyasuto"
    assignees:
      - "nyasuto"
    commit-message:
      prefix: "chore(shared)"
      include: "scope"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "1"
      time: "09:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 3
    reviewers:
      - "nyasuto"
    assignees:
      - "nyasuto"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"