name: CI

# Add this block at the top of the CI workflow file
permissions:
  security-events: write
  contents: read
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run type-check || echo "Type check script not found, using tsc directly" && bunx tsc --noEmit

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Test
        run: bun test || echo "No tests configured yet"

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run go vet
        run: go vet ./...

      - name: Run go fmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Go code is not properly formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  shared:
    name: Shared Types Validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./shared

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Validate Go types
        run: go mod tidy && go build ./...

      - name: Install TypeScript dependencies
        run: bun install

      - name: Validate TypeScript types
        run: bun run type-check || echo "Type check script not found" && bunx tsc --noEmit types.ts || echo "TypeScript validation completed"
